### ISSUE TITLE
Is frameworkcontoller working on kubeadm(not minikube)?

### ISSUE THREAD

**Issue by mf-giwoong-lee** [microsoft/frameworkcontroller#65]
I set kubernetes cluster setting with kubeadm.

I succeeded in setting frameworkcontroller with minikube.

So I firstly set master node and connect worker node to master node.

And run these command lines
```
#kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v0.9.0/nvidia-device-plugin.yml
kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/master/nvidia-device-plugin.yml


kubectl create serviceaccount frameworkcontroller --namespace default
kubectl create clusterrolebinding frameworkcontroller \
  --clusterrole=cluster-admin \
  --user=system:serviceaccount:default:frameworkcontroller


kubectl create -f frameworkcontroller-with-default-config.yaml


kubectl create serviceaccount frameworkbarrier --namespace default
kubectl create clusterrole frameworkbarrier --verb=get,list,watch --resource=frameworks
kubectl create clusterrolebinding frameworkbarrier --clusterrole=frameworkbarrier --user=system:serviceaccount:default:frameworkbarrier
```

After run these cmdlines, I find that the pod about frameworkcontroller falls in CrashBackOff state.

This is the message after running `kubectl describe pod frameworkcontroller-0`

```
Name:         frameworkcontroller-0
Namespace:    default
Priority:     0
Node:         mofl-c246-wu4/192.168.0.28
Start Time:   Mon, 27 Sep 2021 16:58:34 +0900
Labels:       app=frameworkcontroller
              controller-revision-hash=frameworkcontroller-7697d48ff7
              statefulset.kubernetes.io/pod-name=frameworkcontroller-0
Annotations:  <none>
Status:       Running
IP:           172.17.0.8
IPs:
  IP:           172.17.0.8
Controlled By:  StatefulSet/frameworkcontroller
Containers:
  frameworkcontroller:
    Container ID:   docker://c69a07541214fe32fae92a148255d8582d632c01bceb5cd2f887d4dafb86d7ea
    Image:          frameworkcontroller/frameworkcontroller
    Image ID:       docker-pullable://frameworkcontroller/frameworkcontroller@sha256:27674c36f3e5da2cac1249fb6c4fc318e1ab60227c0680cef82695152b442738
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Mon, 27 Sep 2021 17:00:16 +0900
      Finished:     Mon, 27 Sep 2021 17:00:16 +0900
    Ready:          False
    Restart Count:  4
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pdcf2 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  kube-api-access-pdcf2:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  3m11s                 default-scheduler  Successfully assigned default/frameworkcontroller-0 to mofl-c246-wu4
  Normal   Pulled     3m6s                  kubelet            Successfully pulled image "frameworkcontroller/frameworkcontroller" in 2.62030994s
  Normal   Pulled     3m1s                  kubelet            Successfully pulled image "frameworkcontroller/frameworkcontroller" in 2.645024761s
  Normal   Pulled     2m44s                 kubelet            Successfully pulled image "frameworkcontroller/frameworkcontroller" in 2.582812868s
  Normal   Pulled     2m15s                 kubelet            Successfully pulled image "frameworkcontroller/frameworkcontroller" in 2.58364693s
  Normal   Created    2m14s (x4 over 3m5s)  kubelet            Created container frameworkcontroller
  Normal   Started    2m14s (x4 over 3m4s)  kubelet            Started container frameworkcontroller
  Warning  BackOff    106s (x8 over 2m59s)  kubelet            Back-off restarting failed container
  Normal   Pulling    93s (x5 over 3m9s)    kubelet            Pulling image "frameworkcontroller/frameworkcontroller"

```

**Comment by yqwang-ms** [comment]
Pls check the log of frameworkcontroller pod.

**Comment by mf-giwoong-lee** [comment]
```
Error from server: Get "https://192.168.0.28:10250/containerLogs/default/frameworkcontroller-0/frameworkcontroller": dial tcp 192.168.0.28:10250: i/o timeout
```

'kubectl logs frameworkcontroller-0' command gives this error.

So I guess that it is the problem related to kubeadm.

**Comment by mf-giwoong-lee** [comment]
```
I1001 06:23:53.461288       9 controller.go:207] Initializing frameworkcontroller
I1001 06:23:53.464274       9 controller.go:210] With Config:
kubeApiServerAddress: ""
kubeConfigFilePath: ""
kubeClientQps: 80
kubeClientBurst: 120
workerNumber: 200
largeFrameworkCompression: false
crdEstablishedCheckIntervalSec: 1
crdEstablishedCheckTimeoutSec: 60
objectLocalCacheCreationTimeoutSec: 300
frameworkCompletedRetainSec: 2592000
frameworkMinRetryDelaySecForTransientConflictFailed: 60
frameworkMaxRetryDelaySecForTransientConflictFailed: 900
logObjectSnapshot:
  framework:
    onFrameworkRetry: true
    onFrameworkDeletion: true
  task:
    onTaskRetry: true
    onTaskDeletion: true
  pod:
    onPodDeletion: true
podFailureSpec:
- code: -1000
  phrase: PodEvicted
  type:
    name: Failed
    attributes:
    - Transient
  podPatterns:
  - reasonRegex: (?i)^Evicted$
    messageRegex: (?ms).*
- code: -1001
  phrase: PodNodeLost
  type:
    name: Failed
    attributes:
    - Transient
  podPatterns:
  - reasonRegex: (?i)^NodeLost$
    messageRegex: (?ms).*
- code: -1002
  phrase: PodScheduledToInsufficientResourceNode
  type:
    name: Failed
    attributes:
    - Transient
  podPatterns:
  - reasonRegex: (?i)^OutOf\S+$
    messageRegex: (?ms).*
- code: -1003
  phrase: PodPreemptedForCriticalPod
  type:
    name: Failed
    attributes:
    - Transient
  podPatterns:
  - reasonRegex: (?i)^Preempting$
    messageRegex: (?ms).*
- code: -1004
  phrase: PodDeadlineExceeded
  type:
    name: Failed
    attributes:
    - Permanent
  podPatterns:
  - reasonRegex: (?i)^DeadlineExceeded$
    messageRegex: (?ms).*
- code: -1005
  phrase: PodNodeAdmissionForbidden
  type:
    name: Failed
    attributes:
    - Permanent
  podPatterns:
  - reasonRegex: (?i)^Forbidden$
    messageRegex: (?ms).*
- code: -1006
  phrase: PodNodeAdmissionUnexpectedError
  type:
    name: Failed
    attributes:
    - Transient
  podPatterns:
  - reasonRegex: (?i)^UnexpectedAdmissionError$
    messageRegex: (?ms).*
  - reasonRegex: (?i)^UnknownReason$
    messageRegex: (?ms).*
  - reasonRegex: (?i)^InvalidNodeInfo$
    messageRegex: (?ms).*
  - reasonRegex: (?i)^UnexpectedPredicateFailureType$
    messageRegex: (?ms).*
- code: -1200
  phrase: ContainerDockerOOMKilled
  type:
    name: Failed
    attributes:
    - Permanent
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      reasonRegex: (?i)^OOMKilled$
      messageRegex: (?ms).*
      codeRange:
        min: 1
- code: -1201
  phrase: ContainerDockerCreationError
  type:
    name: Failed
    attributes: []
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      reasonRegex: (?i)^ContainerCannotRun$
      messageRegex: (?ms).*
      codeRange:
        min: 125
        max: 125
- code: -1202
  phrase: ContainerDockerStartCmdPermissionDenied
  type:
    name: Failed
    attributes:
    - Permanent
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      reasonRegex: (?i)^ContainerCannotRun$
      messageRegex: (?ms).*
      codeRange:
        min: 126
        max: 126
- code: -1203
  phrase: ContainerDockerStartCmdNotFound
  type:
    name: Failed
    attributes:
    - Permanent
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      reasonRegex: (?i)^ContainerCannotRun$
      messageRegex: (?ms).*
      codeRange:
        min: 127
        max: 127
  - containers:
    - nameRegex: (?ms).*
      reasonRegex: (?i)^ContainerCannotRun$
      messageRegex: (?msi).*(not found|cannot find|no such).*
      codeRange:
        min: 128
        max: 128
- code: -1204
  phrase: ContainerDockerStartUnknownError
  type:
    name: Failed
    attributes: []
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      reasonRegex: (?i)^ContainerCannotRun$
      messageRegex: (?ms).*
      codeRange:
        min: 128
        max: 128
- code: 130
  phrase: ContainerSigIntReceived
  type:
    name: Failed
    attributes:
    - Transient
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      messageRegex: (?ms).*
      codeRange:
        min: 130
        max: 130
- code: 131
  phrase: ContainerSigQuitReceived
  type:
    name: Failed
    attributes:
    - Transient
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      messageRegex: (?ms).*
      codeRange:
        min: 131
        max: 131
- code: 132
  phrase: ContainerSigIllReceived
  type:
    name: Failed
    attributes:
    - Permanent
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      messageRegex: (?ms).*
      codeRange:
        min: 132
        max: 132
- code: 134
  phrase: ContainerSigAbrtReceived
  type:
    name: Failed
    attributes: []
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      messageRegex: (?ms).*
      codeRange:
        min: 134
        max: 134
- code: 135
  phrase: ContainerSigBusReceived
  type:
    name: Failed
    attributes:
    - Permanent
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      messageRegex: (?ms).*
      codeRange:
        min: 135
        max: 135
- code: 136
  phrase: ContainerSigFpeReceived
  type:
    name: Failed
    attributes:
    - Permanent
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      messageRegex: (?ms).*
      codeRange:
        min: 136
        max: 136
- code: 137
  phrase: ContainerSigKillReceived
  type:
    name: Failed
    attributes:
    - Transient
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      messageRegex: (?ms).*
      codeRange:
        min: 137
        max: 137
- code: 139
  phrase: ContainerSigSegvReceived
  type:
    name: Failed
    attributes:
    - Permanent
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      messageRegex: (?ms).*
      codeRange:
        min: 139
        max: 139
- code: 141
  phrase: ContainerSigPipeReceived
  type:
    name: Failed
    attributes:
    - Permanent
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      messageRegex: (?ms).*
      codeRange:
        min: 141
        max: 141
- code: 143
  phrase: ContainerSigTermReceived
  type:
    name: Failed
    attributes:
    - Transient
  podPatterns:
  - containers:
    - nameRegex: (?ms).*
      messageRegex: (?ms).*
      codeRange:
        min: 143
        max: 143
W1001 06:23:53.464335       9 client_config.go:549] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1001 06:23:53.465853       9 controller.go:427] Recovering frameworkcontroller
I1001 06:23:53.482270       9 utils.go:108] Create CRD frameworks.frameworkcontroller.microsoft.com
E1001 06:23:53.487437       9 runtime.go:69] Observed a panic: &errors.errorString{s:"Failed to put CRD: the server could not find the requested resource"} (Failed to put CRD: the server could not find the requested resource)
/go/src/github.com/microsoft/frameworkcontroller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/microsoft/frameworkcontroller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/microsoft/frameworkcontroller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:522
/go/src/github.com/microsoft/frameworkcontroller/pkg/internal/utils.go:66
/go/src/github.com/microsoft/frameworkcontroller/pkg/controller/controller.go:428
/go/src/github.com/microsoft/frameworkcontroller/cmd/frameworkcontroller/main.go:35
/usr/local/go/src/runtime/proc.go:200
/usr/local/go/src/runtime/asm_amd64.s:1337
E1001 06:23:53.487486       9 panic.go:522] Stopping frameworkcontroller
panic: Failed to put CRD: the server could not find the requested resource [recovered]
        panic: Failed to put CRD: the server could not find the requested resource

goroutine 1 [running]:
github.com/microsoft/frameworkcontroller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/microsoft/frameworkcontroller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x11f84e0, 0xc00019c0e0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/microsoft/frameworkcontroller/pkg/internal.PutCRD(0xc000314960, 0xc0004e2000, 0xc00035d0a8, 0xc00035d0b0)
        /go/src/github.com/microsoft/frameworkcontroller/pkg/internal/utils.go:66 +0x173
github.com/microsoft/frameworkcontroller/pkg/controller.(*FrameworkController).Run(0xc0000e93f0, 0xc0000cb140)
        /go/src/github.com/microsoft/frameworkcontroller/pkg/controller/controller.go:428 +0x157
main.main()
        /go/src/github.com/microsoft/frameworkcontroller/cmd/frameworkcontroller/main.go:35 +0x47
```

This is log message...

I set the pod network with calico and re-launch cmdlines about frameworkcontroller

**Comment by yqwang-ms** [comment]
something wrong in your cluster, pls search web to find solution, such as https://github.com/kubernetes/kubernetes/issues/9945
